version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=ledgerdb

  # go-server:
  #   image: go-server
  #   container_name: go-server
  #   ports:
  #     - "8080:8080"
